/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as registrar from "./registrar";
export type { registrar };
import type * as registry from "./registry";
export type { registry };
