/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mock from "./mock";
export type { mock };
export type { Auction } from "./Auction";
export type { Errors } from "./Errors";
export type { IAuction } from "./IAuction";
export type { IRegistrar } from "./IRegistrar";
export type { Registrar } from "./Registrar";
