/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IRegistrar {
  export type CommitParamStruct = { secret: string; value: BigNumberish };

  export type CommitParamStructOutput = [secret: string, value: bigint] & {
    secret: string;
    value: bigint;
  };
}

export interface IRegistrarInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "auctionDeadline"
      | "auctionHighestBid"
      | "auctionHighestBidder"
      | "batchRevealRegister"
      | "commit"
      | "expiry"
      | "getAuctionDuration"
      | "getDomainCurrentVersion"
      | "getDomainFutureVersion"
      | "hasAuctionExpired"
      | "hasCommitment"
      | "hasDomainExpired"
      | "makeDomainCommitment"
      | "makeDomainPreCommitment"
      | "precommit"
      | "revealRegister"
      | "setCName"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DomainAuctionStarted"
      | "DomainBidFailed"
      | "DomainRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "auctionDeadline",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "auctionHighestBid",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "auctionHighestBidder",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "batchRevealRegister",
    values: [string, IRegistrar.CommitParamStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "commit",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "expiry", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getAuctionDuration",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDomainCurrentVersion",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDomainFutureVersion",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasAuctionExpired",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasCommitment",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasDomainExpired",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "makeDomainCommitment",
    values: [BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "makeDomainPreCommitment",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "precommit",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revealRegister",
    values: [string, IRegistrar.CommitParamStruct]
  ): string;
  encodeFunctionData(functionFragment: "setCName", values: [string]): string;

  decodeFunctionResult(
    functionFragment: "auctionDeadline",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "auctionHighestBid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "auctionHighestBidder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchRevealRegister",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "commit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "expiry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAuctionDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDomainCurrentVersion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDomainFutureVersion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasAuctionExpired",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasCommitment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasDomainExpired",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "makeDomainCommitment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "makeDomainPreCommitment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "precommit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "revealRegister",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setCName", data: BytesLike): Result;
}

export namespace DomainAuctionStartedEvent {
  export type InputTuple = [
    domainHash: BytesLike,
    tld: string,
    domain: string,
    duration: BigNumberish,
    deadline: BigNumberish
  ];
  export type OutputTuple = [
    domainHash: string,
    tld: string,
    domain: string,
    duration: bigint,
    deadline: bigint
  ];
  export interface OutputObject {
    domainHash: string;
    tld: string;
    domain: string;
    duration: bigint;
    deadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DomainBidFailedEvent {
  export type InputTuple = [
    owner: AddressLike,
    tldHash: BytesLike,
    domainHash: BytesLike,
    tld: string,
    domain: string,
    expires: BigNumberish,
    refund: BigNumberish,
    highestBid: BigNumberish,
    highestCommitment: BytesLike
  ];
  export type OutputTuple = [
    owner: string,
    tldHash: string,
    domainHash: string,
    tld: string,
    domain: string,
    expires: bigint,
    refund: bigint,
    highestBid: bigint,
    highestCommitment: string
  ];
  export interface OutputObject {
    owner: string;
    tldHash: string;
    domainHash: string;
    tld: string;
    domain: string;
    expires: bigint;
    refund: bigint;
    highestBid: bigint;
    highestCommitment: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DomainRegisteredEvent {
  export type InputTuple = [
    owner: AddressLike,
    tldHash: BytesLike,
    domainHash: BytesLike,
    tld: string,
    domain: string,
    expires: BigNumberish,
    cost: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    owner: string,
    tldHash: string,
    domainHash: string,
    tld: string,
    domain: string,
    expires: bigint,
    cost: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    owner: string;
    tldHash: string;
    domainHash: string;
    tld: string;
    domain: string;
    expires: bigint;
    cost: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IRegistrar extends BaseContract {
  connect(runner?: ContractRunner | null): IRegistrar;
  waitForDeployment(): Promise<this>;

  interface: IRegistrarInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  auctionDeadline: TypedContractMethod<[label: BytesLike], [bigint], "view">;

  auctionHighestBid: TypedContractMethod<[label: BytesLike], [bigint], "view">;

  auctionHighestBidder: TypedContractMethod<
    [label: BytesLike],
    [string],
    "view"
  >;

  batchRevealRegister: TypedContractMethod<
    [domain: string, commitments: IRegistrar.CommitParamStruct[]],
    [void],
    "nonpayable"
  >;

  commit: TypedContractMethod<
    [domain: string, secret: BytesLike],
    [void],
    "nonpayable"
  >;

  expiry: TypedContractMethod<[domain: BytesLike], [bigint], "view">;

  getAuctionDuration: TypedContractMethod<[], [bigint], "view">;

  getDomainCurrentVersion: TypedContractMethod<
    [domain: BytesLike],
    [string],
    "view"
  >;

  getDomainFutureVersion: TypedContractMethod<
    [domain: BytesLike],
    [string],
    "view"
  >;

  hasAuctionExpired: TypedContractMethod<[label: BytesLike], [boolean], "view">;

  hasCommitment: TypedContractMethod<
    [commitment: BytesLike],
    [boolean],
    "view"
  >;

  hasDomainExpired: TypedContractMethod<[domain: BytesLike], [boolean], "view">;

  makeDomainCommitment: TypedContractMethod<
    [domain: BytesLike, secret: BytesLike, value: BigNumberish],
    [string],
    "view"
  >;

  makeDomainPreCommitment: TypedContractMethod<
    [domain: BytesLike, secret: BytesLike],
    [string],
    "view"
  >;

  precommit: TypedContractMethod<[precommitment: BytesLike], [void], "payable">;

  revealRegister: TypedContractMethod<
    [domain: string, param: IRegistrar.CommitParamStruct],
    [boolean],
    "nonpayable"
  >;

  setCName: TypedContractMethod<[domain: string], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "auctionDeadline"
  ): TypedContractMethod<[label: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "auctionHighestBid"
  ): TypedContractMethod<[label: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "auctionHighestBidder"
  ): TypedContractMethod<[label: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "batchRevealRegister"
  ): TypedContractMethod<
    [domain: string, commitments: IRegistrar.CommitParamStruct[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "commit"
  ): TypedContractMethod<
    [domain: string, secret: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "expiry"
  ): TypedContractMethod<[domain: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAuctionDuration"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDomainCurrentVersion"
  ): TypedContractMethod<[domain: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getDomainFutureVersion"
  ): TypedContractMethod<[domain: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "hasAuctionExpired"
  ): TypedContractMethod<[label: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "hasCommitment"
  ): TypedContractMethod<[commitment: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "hasDomainExpired"
  ): TypedContractMethod<[domain: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "makeDomainCommitment"
  ): TypedContractMethod<
    [domain: BytesLike, secret: BytesLike, value: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "makeDomainPreCommitment"
  ): TypedContractMethod<
    [domain: BytesLike, secret: BytesLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "precommit"
  ): TypedContractMethod<[precommitment: BytesLike], [void], "payable">;
  getFunction(
    nameOrSignature: "revealRegister"
  ): TypedContractMethod<
    [domain: string, param: IRegistrar.CommitParamStruct],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setCName"
  ): TypedContractMethod<[domain: string], [void], "nonpayable">;

  getEvent(
    key: "DomainAuctionStarted"
  ): TypedContractEvent<
    DomainAuctionStartedEvent.InputTuple,
    DomainAuctionStartedEvent.OutputTuple,
    DomainAuctionStartedEvent.OutputObject
  >;
  getEvent(
    key: "DomainBidFailed"
  ): TypedContractEvent<
    DomainBidFailedEvent.InputTuple,
    DomainBidFailedEvent.OutputTuple,
    DomainBidFailedEvent.OutputObject
  >;
  getEvent(
    key: "DomainRegistered"
  ): TypedContractEvent<
    DomainRegisteredEvent.InputTuple,
    DomainRegisteredEvent.OutputTuple,
    DomainRegisteredEvent.OutputObject
  >;

  filters: {
    "DomainAuctionStarted(bytes32,string,string,uint256,uint256)": TypedContractEvent<
      DomainAuctionStartedEvent.InputTuple,
      DomainAuctionStartedEvent.OutputTuple,
      DomainAuctionStartedEvent.OutputObject
    >;
    DomainAuctionStarted: TypedContractEvent<
      DomainAuctionStartedEvent.InputTuple,
      DomainAuctionStartedEvent.OutputTuple,
      DomainAuctionStartedEvent.OutputObject
    >;

    "DomainBidFailed(address,bytes32,bytes32,string,string,uint256,uint256,uint256,bytes32)": TypedContractEvent<
      DomainBidFailedEvent.InputTuple,
      DomainBidFailedEvent.OutputTuple,
      DomainBidFailedEvent.OutputObject
    >;
    DomainBidFailed: TypedContractEvent<
      DomainBidFailedEvent.InputTuple,
      DomainBidFailedEvent.OutputTuple,
      DomainBidFailedEvent.OutputObject
    >;

    "DomainRegistered(address,bytes32,bytes32,string,string,uint256,uint256,uint256)": TypedContractEvent<
      DomainRegisteredEvent.InputTuple,
      DomainRegisteredEvent.OutputTuple,
      DomainRegisteredEvent.OutputObject
    >;
    DomainRegistered: TypedContractEvent<
      DomainRegisteredEvent.InputTuple,
      DomainRegisteredEvent.OutputTuple,
      DomainRegisteredEvent.OutputObject
    >;
  };
}
