/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as mock from "./mock";
export { Auction__factory } from "./Auction__factory";
export { Errors__factory } from "./Errors__factory";
export { IAuction__factory } from "./IAuction__factory";
export { IRegistrar__factory } from "./IRegistrar__factory";
export { Registrar__factory } from "./Registrar__factory";
