/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DNSRegistry__factory } from "./DNSRegistry__factory";
export { IDNS__factory } from "./IDNS__factory";
