/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DNSRegistry } from "./DNSRegistry";
export type { Errors } from "./Errors";
export type { IDNS } from "./IDNS";
